# Instructions to run:
# cd to folder containing this file
# conda env create
# source activate ml-infn

name: ml-infn
dependencies:
- python=2.7
- pandas>=0.19.0
- numpy>=1.11.2
- scikit-learn>=0.18
- scipy>=0.18.1
- matplotlib>=1.5.3
- jupyter>=1.0
- ipython>=5.1
- seaborn>=0.7
