name: dl-infn
channels: !!python/tuple
- !!python/unicode
  'defaults'
- 'conda-forge'
dependencies:
- python=2.7
- h5py=2.6.0
- jupyter=1.0.0
- matplotlib=1.5.3
- pandas=0.19.1
- scikit-learn=0.18.1
- scipy=0.18.1
- tensorflow=0.11
- seaborn>=0.7
- pip:
  - keras==1.1.1
