name: dl-infn
dependencies:
- python=2.7
- h5py=2.6.0
- jupyter=1.0.0
- matplotlib=1.5.1
- pandas=0.18.1
- scikit-learn=0.17.1
- scipy=0.17.1
- pip:
  - keras==1.0.5
  - https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py2-none-any.whl
